{% set name = "dvc-studio-client" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvc-studio-client-{{ version }}.tar.gz
  sha256: dabe29fbf55795de82faf8157a35fa9c00fe0553867ef8013281503607a1f66b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - gitpython
    - python >=3.8
    - requests
    - voluptuous

test:
  imports:
    - dvc_studio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/dvc-studio-client
  summary: Small library to post data from DVC/DVCLive to Iterative Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
